
spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://h1.host.filess.io:3306/TodoDB_mindpolein
    username: TodoDB_mindpolein
    password: 8aaddee681ac4fdded2b7383a7c68ba34f7c0429
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
  main:
    allow-circular-references: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type: TRACE
server:
  port: 5003
jwt:
  secret: secret
  expirationTimeInMS: 3000000













